name: 并购数据日报__html_pdf
on:
  schedule:
    - cron: '00 08 * * *'  # 定时触发
  workflow_dispatch:      # 手动触发（新增）
    inputs:
      test_mode:
        description: '是否以测试模式运行'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas jinja2 pdfkit
      - name: 执行脚本
        run: python 生成并购重组PDF报告.py
      - name: 保存结果
        uses: actions/upload-artifact@v3
        with:
          name: report-files
          path: ./*.pdf  # 自动保存生成的PDF文件
